"use client";

import { useEffect, useMemo, useState } from "react";
import { Package, Pencil, Plus, RefreshCw, Search, SlidersHorizontal, Trash2, X } from "lucide-react";
import Modal from "@/components/ui/Modal";
import ProductImageManager from "@/components/dashboard/ProductImageManager";
import type { Category, Product, ProductImage } from "@/lib/types";

type Form = { title: string; brand: string; sku: string; category: string; price: number; discount: number; purchaseCost: number; stock: number };
const emptyForm: Form = { title: "", brand: "", sku: "", category: "", price: 0, discount: 0, purchaseCost: 0, stock: 0 };

export default function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [stockFilter, setStockFilter] = useState<"all" | "low" | "out">("all"); const [sort, setSort] = useState<"newest" | "price-low" | "price-high" | "stock-low">("newest");
  const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Product | null>(null); const [form, setForm] = useState<Form>(emptyForm); const [images, setImages] = useState<ProductImage[]>([]); const [pendingFiles, setPendingFiles] = useState<File[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState("");

  async function load() { setLoading(true); try { const [a,b] = await Promise.all([fetch("/api/admin/products", { cache: "no-store" }).then(r=>r.json()), fetch("/api/admin/categories", { cache: "no-store" }).then(r=>r.json())]); setProducts(a.success ? a.data : []); setCategories(b.success ? b.data : []); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);

  const filtered = useMemo(() => { const q=query.trim().toLowerCase(); return products.filter(p => (!q || `${p.title} ${p.brand} ${p.sku} ${p.category}`.toLowerCase().includes(q)) && (!category || p.category===category) && (stockFilter==="all" || (stockFilter==="out" ? p.stock<=0 : p.stock>0 && p.stock<=5))).sort((a,b) => sort==="price-low" ? a.price-b.price : sort==="price-high" ? b.price-a.price : sort==="stock-low" ? a.stock-b.stock : String(b.updatedAt||b.createdAt||"").localeCompare(String(a.updatedAt||a.createdAt||""))); }, [products,query,category,stockFilter,sort]);

  function openCreate(){ setEditing(null); setForm(emptyForm); setImages([]); setPendingFiles([]); setError(""); setModal(true); }
  function openEdit(p: Product){ setEditing(p); setForm({title:p.title,brand:p.brand,sku:p.sku,category:p.category,price:p.price,discount:p.discount,purchaseCost:p.purchaseCost||0,stock:p.stock}); setImages(p.images || (p.image ? [{id:`legacy-${p.id}`,url:p.image,alt:p.title,position:0,createdAt:p.createdAt||""}] : [])); setPendingFiles([]); setError(""); setModal(true); }

  async function uploadPending(productId: string) { if (!pendingFiles.length) return; const fd=new FormData(); pendingFiles.forEach(f=>fd.append("files",f)); const r=await fetch(`/api/admin/products/${productId}/images`,{method:"POST",body:fd}); const j=await r.json(); if(!r.ok||!j.success) throw new Error(j.error?.message||"آپلود تصاویر انجام نشد."); }
  async function save(){ if(!form.title.trim()||!form.sku.trim()||!form.category.trim()){setError("نام محصول، SKU و دسته‌بندی الزامی است.");return;} setSaving(true);setError(""); try { const r=await fetch(editing?`/api/admin/products/${editing.id}`:"/api/admin/products",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,title:form.title.trim(),sku:form.sku.trim(),category:form.category.trim(),image:images[0]?.url||editing?.image||"",images})}); const j=await r.json(); if(!r.ok||!j.success) throw new Error(j.error?.message||"ذخیره محصول انجام نشد."); if(!editing) await uploadPending(j.data.id); setModal(false); await load(); } catch(e){setError(e instanceof Error?e.message:"خطا در ارتباط با سرور.");} finally{setSaving(false);} }
  async function remove(p: Product){ if(!confirm(`محصول «${p.title}» حذف شود؟`))return; const r=await fetch(`/api/admin/products/${p.id}`,{method:"DELETE"}); const j=await r.json(); if(!r.ok||!j.success){alert(j.error?.message||"حذف محصول انجام نشد.");return;} await load(); }
  function clearFilters(){setQuery("");setCategory("");setStockFilter("all");setSort("newest");}

  return <div className="mx-auto max-w-[1500px]">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-black text-[var(--primary)]">کاتالوگ و موجودی</div><h1 className="mt-1 text-3xl font-black tracking-tight">محصولات</h1><p className="mt-2 text-sm text-[var(--muted)]">{filtered.length} محصول از {products.length} محصول</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="btn btn-secondary" type="button"><RefreshCw size={17}/>بروزرسانی</button><button onClick={openCreate} className="btn btn-primary" type="button"><Plus size={17}/>محصول جدید</button></div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="card p-4"><div className="text-xs font-bold text-[var(--muted)]">کل محصولات</div><div className="mt-1 text-2xl font-black">{products.length}</div></div><div className="card p-4"><div className="text-xs font-bold text-[var(--muted)]">موجودی کم</div><div className="mt-1 text-2xl font-black text-[var(--warning)]">{products.filter(p=>p.stock>0&&p.stock<=5).length}</div></div><div className="card p-4"><div className="text-xs font-bold text-[var(--muted)]">ناموجود</div><div className="mt-1 text-2xl font-black text-[var(--danger)]">{products.filter(p=>p.stock<=0).length}</div></div></div>
    <div className="card mt-5 p-4"><div className="flex flex-wrap items-center gap-3"><div className="relative min-w-[240px] flex-1"><Search className="absolute right-3 top-3.5 text-[var(--muted)]" size={17}/><input className="input pr-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجو: نام، برند، SKU یا دسته‌بندی..."/></div><select className="input w-full sm:w-52" value={category} onChange={e=>setCategory(e.target.value)}><option value="">همه دسته‌بندی‌ها</option>{categories.filter(c=>c.active!==false).map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select><select className="input w-full sm:w-44" value={stockFilter} onChange={e=>setStockFilter(e.target.value as typeof stockFilter)}><option value="all">همه موجودی‌ها</option><option value="low">موجودی کم</option><option value="out">ناموجود</option></select><select className="input w-full sm:w-44" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="newest">جدیدترین</option><option value="price-low">ارزان‌ترین</option><option value="price-high">گران‌ترین</option><option value="stock-low">کمترین موجودی</option></select>{(query||category||stockFilter!=="all"||sort!=="newest")&&<button onClick={clearFilters} className="btn btn-secondary" type="button"><X size={16}/>پاک کردن</button>}</div><div className="mt-3 flex items-center gap-2 text-xs text-[var(--muted)]"><SlidersHorizontal size={14}/>گالری، تصویر اصلی و تصویر Hover از همین بخش مدیریت می‌شوند.</div></div>
    <div className="card mt-5 overflow-hidden">{loading?<div className="p-12 text-center text-sm text-[var(--muted)]">در حال دریافت محصولات...</div>:!filtered.length?<div className="p-12 text-center"><Package className="mx-auto text-[var(--muted)]" size={30}/><div className="mt-3 font-black">محصولی پیدا نشد</div></div>:<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-right text-sm"><thead className="bg-[var(--surface-2)] text-[11px] font-black text-[var(--muted)]"><tr><th className="p-4">محصول</th><th className="p-4">دسته‌بندی</th><th className="p-4">SKU</th><th className="p-4">قیمت</th><th className="p-4">خرید</th><th className="p-4">موجودی</th><th className="p-4">عملیات</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="border-t border-[var(--border)] hover:bg-[var(--surface-2)]"><td className="p-4"><div className="flex items-center gap-3"><div className="size-12 shrink-0 overflow-hidden rounded-xl bg-[var(--surface-2)]">{(p.images?.[0]?.url||p.image)?<img src={p.images?.[0]?.url||p.image} alt={p.title} className="size-full object-cover"/>:<Package className="m-auto mt-3 text-[var(--muted)]" size={18}/>}</div><div><div className="font-black">{p.title}</div><div className="mt-1 text-xs text-[var(--muted)]">{p.brand||"بدون برند"} · {(p.images?.length||0).toLocaleString("fa-IR")} تصویر</div></div></div></td><td className="p-4"><span className="badge bg-[var(--primary)]/10 text-[var(--primary)]">{p.category}</span></td><td className="p-4 font-mono text-xs">{p.sku}</td><td className="p-4 font-black">{p.price.toLocaleString("fa-IR")} تومان</td><td className="p-4 text-[var(--muted)]">{Number(p.purchaseCost||0).toLocaleString("fa-IR")} تومان</td><td className="p-4"><span className={`font-black ${p.stock<=0?"text-[var(--danger)]":p.stock<=5?"text-[var(--warning)]":""}`}>{p.stock.toLocaleString("fa-IR")}</span></td><td className="p-4"><div className="flex gap-2"><button onClick={()=>openEdit(p)} className="btn btn-secondary !p-2" type="button"><Pencil size={15}/></button><button onClick={()=>void remove(p)} className="btn btn-danger !p-2" type="button"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}</div>
    {modal&&<Modal title={editing?"ویرایش محصول":"ثبت محصول جدید"} onClose={()=>!saving&&setModal(false)}><div className="grid gap-3 sm:grid-cols-2">{error&&<div className="sm:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</div>}<div className="sm:col-span-2"><label className="field-label">نام محصول</label><input className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div><label className="field-label">برند</label><input className="input" value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></div><div><label className="field-label">SKU</label><input dir="ltr" className="input text-left" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></div><div><label className="field-label">دسته‌بندی</label><select className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">انتخاب دسته‌بندی</option>{categories.filter(c=>c.active!==false).map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div><div><label className="field-label">قیمت فروش</label><input className="input" type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)||0})}/></div><div><label className="field-label">قیمت خرید</label><input className="input" type="number" min="0" value={form.purchaseCost} onChange={e=>setForm({...form,purchaseCost:Number(e.target.value)||0})}/></div><div><label className="field-label">تخفیف (%)</label><input className="input" type="number" min="0" max="100" value={form.discount} onChange={e=>setForm({...form,discount:Number(e.target.value)||0})}/></div><div><label className="field-label">موجودی</label><input className="input" type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)||0})}/></div><ProductImageManager productId={editing?.id} images={images} onChange={setImages} onPendingFiles={setPendingFiles}/><button disabled={saving} onClick={()=>void save()} className="btn btn-primary sm:col-span-2 disabled:opacity-60" type="button">{saving?"در حال ذخیره...":"ذخیره محصول"}</button></div></Modal>}
  </div>;
}
