import { ok, fail } from "@/lib/http";
import { requirePermission } from "@/lib/permissions";
import { getJson, writeJson } from "@/lib/github";
import { normalizeProduct } from "@/lib/data";
import type { Product } from "@/lib/types";
const allowed=new Set(["products","customers","suppliers","sales","sale-items","purchases","purchase-items","inventory","finance","checks","quotations","expenses","incomes","brands","categories","settings","activity-logs"]);
const perms:Record<string,string>={products:"products",customers:"customers",suppliers:"suppliers",sales:"sales","sale-items":"sales",purchases:"purchases","purchase-items":"purchases",inventory:"inventory",finance:"finance",checks:"checks",quotations:"quotations",expenses:"finance",incomes:"finance",brands:"products",categories:"products",settings:"settings","activity-logs":"settings"};
export async function GET(req:Request,{params}:{params:Promise<{collection:string}>}){try{const{collection}=await params;if(!allowed.has(collection))throw new Error("NOT_FOUND");await requirePermission(`${perms[collection]}.read`);const data=(await getJson<any[]>(`${collection}.json`,[])).data;return ok(collection==="products"?data.map((item)=>normalizeProduct(item as Product)):data);}catch(e){return fail(e)}}
export async function POST(req:Request,{params}:{params:Promise<{collection:string}>}){try{const{collection}=await params;if(!allowed.has(collection))throw new Error("NOT_FOUND");await requirePermission(`${perms[collection]}.create`);const body=await req.json();const f=await getJson<any[]>(`${collection}.json`,[]);const item={...body,id:crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};f.data.push(collection==="products"?normalizeProduct(item as Product):item);await writeJson(`${collection}.json`,f.data,`Create ${collection}/${item.id}`,f.sha||undefined);return ok(item,201);}catch(e){return fail(e)}}
