"use client";
import { useEffect, useState } from "react";
import { Plus, Pencil, Trash2, RefreshCw } from "lucide-react";
import Modal from "@/components/ui/Modal";
type User={id:string;name:string;phone:string;role:string;createdAt?:string};
const empty={name:"",phone:"",password:""};
export default function UsersPage(){
 const [rows,setRows]=useState<User[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<User|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/users',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message||'خطا');setRows(j.data)}catch(e){setError(e instanceof Error?e.message:'خطا')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function create(){setEditing(null);setForm(empty);setError("");setOpen(true)}
 function edit(u:User){setEditing(u);setForm({name:u.name,phone:u.phone,password:""});setError("");setOpen(true)}
 async function save(){if(!form.name||!form.phone||(!editing&&!form.password)){setError('نام، موبایل و در حالت ایجاد رمز عبور الزامی است.');return}setSaving(true);setError("");try{const r=await fetch(editing?`/api/admin/users/${editing.id}`:'/api/admin/users',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message||'ذخیره انجام نشد');setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'خطا')}finally{setSaving(false)}}
 async function remove(u:User){if(!confirm(`کاربر «${u.name}» حذف شود؟`))return;const r=await fetch(`/api/admin/users/${u.id}`,{method:'DELETE'});const j=await r.json();if(!r.ok||!j.success){alert(j.error?.message||'حذف انجام نشد');return}load()}
 return <div className="mx-auto max-w-[1400px]"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-black text-[var(--primary)]">امنیت و دسترسی</div><h1 className="mt-1 text-3xl font-black">کاربران مدیر</h1></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={()=>void load()}><RefreshCw size={17}/>بروزرسانی</button><button className="btn btn-primary" onClick={create}><Plus size={17}/>کاربر جدید</button></div></div><div className="card mt-6 overflow-hidden">{loading?<div className="p-10 text-center text-[var(--muted)]">در حال دریافت...</div>:<div className="overflow-auto"><table className="w-full min-w-[700px] text-right text-sm"><thead className="bg-[var(--surface-2)] text-xs text-[var(--muted)]"><tr><th className="p-4">نام</th><th className="p-4">موبایل</th><th className="p-4">نقش</th><th className="p-4">تاریخ</th><th className="p-4">عملیات</th></tr></thead><tbody>{rows.map(u=><tr key={u.id} className="border-t border-[var(--border)]"><td className="p-4 font-bold">{u.name}</td><td className="p-4">{u.phone}</td><td className="p-4">مدیر</td><td className="p-4">{u.createdAt?new Date(u.createdAt).toLocaleDateString('fa-IR'):'—'}</td><td className="p-4"><div className="flex gap-2"><button className="btn btn-secondary !p-2" onClick={()=>edit(u)}><Pencil size={15}/></button><button className="btn btn-danger !p-2" onClick={()=>void remove(u)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}</div>{open&&<Modal title={editing?'ویرایش کاربر':'ایجاد کاربر مدیر'} onClose={()=>!saving&&setOpen(false)}><div className="space-y-3">{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div><label className="field-label">نام</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="field-label">موبایل</label><input className="input" dir="ltr" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="field-label">رمز عبور {editing&&'(در صورت تغییر وارد کنید)'}</label><input className="input" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><button disabled={saving} className="btn btn-primary w-full" onClick={()=>void save()}>{saving?'در حال ذخیره...':'ذخیره'}</button></div></Modal>}</div>
}
