"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { FileImage, LogOut, ShieldCheck } from "lucide-react";
import type { Session } from "@/lib/auth";
import type { Sale } from "@/lib/types";

const labels:Record<string,string>={PAID:"پرداخت تأیید شد",PENDING_TRANSFER:"در انتظار بررسی فیش",PARTIAL:"پرداخت جزئی",CANCELED:"لغو شده"};
export default function AccountOverview({session}:{session:Pick<Session,"id"|"name"|"phone"|"role">}){const router=useRouter();const[loading,setLoading]=useState(false);const[orders,setOrders]=useState<Sale[]>([]);
useEffect(()=>{if(session.role!=="CUSTOMER")return;fetch("/api/account/orders",{cache:"no-store"}).then(r=>r.json()).then(j=>j.success&&setOrders(j.data)).catch(()=>{});},[session.role]);
async function logout(){setLoading(true);await fetch("/api/auth/logout",{method:"POST"});router.push("/");router.refresh();}
return <div><div className="text-sm font-bold text-[var(--primary)]">حساب کاربری</div><h1 className="mt-2 text-2xl font-black">{session.name}</h1><div className="mt-1 text-sm text-[var(--muted)]">{session.phone}</div><div className="mt-5 inline-flex items-center gap-2 rounded-full bg-[var(--primary)]/10 px-3 py-2 text-xs font-bold text-[var(--primary)]"><ShieldCheck size={15}/>{session.role==="ADMIN"?"مدیر سیستم":"مشتری"}</div>{session.role==="CUSTOMER"&&<section className="mt-8"><div className="flex items-center justify-between"><h2 className="font-black">سفارش‌های من</h2><span className="text-xs text-[var(--muted)]">{orders.length.toLocaleString("fa-IR")} سفارش</span></div>{!orders.length?<div className="mt-3 rounded-2xl bg-[var(--surface-2)] p-5 text-sm text-[var(--muted)]">هنوز سفارشی ثبت نکرده‌اید.</div>:<div className="mt-3 space-y-3">{orders.map(order=><article key={order.id} className="rounded-2xl border border-[var(--border)] p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-black">سفارش #{order.id.slice(0,8)}</div><div className="mt-1 text-xs text-[var(--muted)]">{new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium",timeZone:"Asia/Tehran"}).format(new Date(order.createdAt))}</div></div><span className="badge bg-[var(--surface-2)]">{labels[order.paymentStatus]||order.paymentStatus}</span></div><div className="mt-4 text-sm font-black">{Number(order.netAmount).toLocaleString("fa-IR")} تومان</div>{order.receiptImage&&<a href={order.receiptImage} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-[var(--primary)]"><FileImage size={14}/>مشاهده فیش واریزی</a>}</article>)}</div>}</section>}<div className="mt-7 space-y-2">{session.role==="ADMIN"&&<button onClick={()=>router.push("/dashboard")} className="btn btn-primary w-full" type="button">ورود به پنل مدیریت</button>}<button onClick={()=>void logout()} disabled={loading} className="btn btn-danger w-full disabled:opacity-60" type="button"><LogOut size={17}/>{loading?"در حال خروج...":"خروج از حساب"}</button></div></div>}
